---
- name: Install linOTP
  hosts: all
  remote_user: ubuntu
  become: yes

  roles:
  - engin

  ---
- hosts: all
  tasks:
  - name: Package installation
    yum:
      name:
        - sysstat
        - httpd
        - mariadb-server
      state: latest



---
# Step 1: Prepare EC2 instance for RADIUS services

# Connect to the EC2 instance via SSH. Make sure that it is up-to-date, and enable the repository.
    sudo yum -y update
    sudo amazon-linux-extras install epel -y
    sudo yum localinstall http://dist.linotp.org/rpm/el7/linotp/x86_64/Packages/LinOTP_repos-1.1-1.el7.x86_64.rpm -y
    sed -i 's,http://linotp.org/rpm/el7/dependencies/x86_64, http://dist.linotp.org/rpm/el7/dependencies/x86_64,g' /etc/yum.repos.d/linotp.repo
    sed -i 's,http://linotp.org/rpm/el7/linotp/x86_64, http://dist.linotp.org/rpm/el7/linotp/x86_64,g' /etc/yum.repos.d/linotp.repo

# Install MariaDB, enable the service and secure the database. Confirm steps to lockdown MariaDB, like removing the Root privilege for login into MariaDB, or setting Root password to something different.
    sudo yum install mariadb-server -y
    sudo systemctl enable mariadb
    sudo systemctl start mariadb
    sudo mysql_secure_installation

# Install LinOTP, Apache httpd and configure with MariaDB
    sudo yum install -y LinOTP LinOTP_mariadb
    sudo restorecon -Rv /etc/linotp2/
    sudo restorecon -Rv /var/log/linotp
    
    # Configure LinOTP and MariaDB credentials
    sudo linotp-create-mariadb
   
    # Lock python-repoze-who version
    sudo yum install yum-plugin-versionlock -y
    sudo yum versionlock python-repoze-who
   
    # Install apache and vhost config
    sudo yum install LinOTP_apache -y
    sudo systemctl enable httpd
    sudo systemctl start httpd
    sudo mv /etc/httpd/conf.d/ssl.conf /etc/httpd/conf.d/ssl.conf.back
    sudo mv /etc/httpd/conf.d/ssl_linotp.conf.template /etc/httpd/conf.d/ssl_linotp.conf



