---
- name: Install linOTP
  hosts: all
  remote_user: ubuntu
  become: yes

  roles:
  - engin

  ---
- hosts: all
  tasks:
  - name: Package installation
    yum:
      name:
        - sysstat
        - httpd
        - mariadb-server
      state: latest
